// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFInPX0imS12duW56VJPeULWEuhEUsG8',
    appId: '1:392500343292:web:38efebbfcd42b23a554279',
    messagingSenderId: '392500343292',
    projectId: 'codeandwin-fb840',
    authDomain: 'codeandwin-fb840.firebaseapp.com',
    storageBucket: 'codeandwin-fb840.firebasestorage.app',
    measurementId: 'G-T5L6JWJXSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-p7ITGQB65IlulCIzwhUj6WR34gVbak',
    appId: '1:392500343292:android:ff408197d0426ad0554279',
    messagingSenderId: '392500343292',
    projectId: 'codeandwin-fb840',
    storageBucket: 'codeandwin-fb840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8THiBIDTU2Q1on6SoKiTmUinkpL2Wt4',
    appId: '1:392500343292:ios:f2e8a8011a2567f5554279',
    messagingSenderId: '392500343292',
    projectId: 'codeandwin-fb840',
    storageBucket: 'codeandwin-fb840.firebasestorage.app',
    iosBundleId: 'com.example.startupMobileapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8THiBIDTU2Q1on6SoKiTmUinkpL2Wt4',
    appId: '1:392500343292:ios:f2e8a8011a2567f5554279',
    messagingSenderId: '392500343292',
    projectId: 'codeandwin-fb840',
    storageBucket: 'codeandwin-fb840.firebasestorage.app',
    iosBundleId: 'com.example.startupMobileapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjFInPX0imS12duW56VJPeULWEuhEUsG8',
    appId: '1:392500343292:web:6f087797beda2f76554279',
    messagingSenderId: '392500343292',
    projectId: 'codeandwin-fb840',
    authDomain: 'codeandwin-fb840.firebaseapp.com',
    storageBucket: 'codeandwin-fb840.firebasestorage.app',
    measurementId: 'G-ND1B10KLF9',
  );

}